//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.6
//
package com.old.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
            "MobileHub 0ba38524-d5cc-4979-a119-1f936d366dc0 aws-my-sample-app-android-v0.6";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
            Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
            "us-east-1:4bb5f85b-f014-4f7b-a2af-1dcaad5dd012";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
            "threeinthemorning-userfiles-mobilehub-807719108";
}
//public class AWSConfiguration {
//
//    // AWS MobileHub user agent string
//    public static final String AWS_MOBILEHUB_USER_AGENT =
//        "MobileHub a2768eb0-0e59-41a9-9ee0-0e0f4218d4fc aws-my-sample-app-android-v0.6";
//    // AMAZON COGNITO
//    public static final Regions AMAZON_COGNITO_REGION =
//        Regions.US_EAST_1;
//    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
//        "us-east-1:dc593158-2258-4ded-aea3-f27eca809e3f";
//    // Google Client ID for Web application
////    public static final String GOOGLE_CLIENT_ID =
////        "128301925266-8qoirq89o0ikmrssgp2rkjec2r30g3cd.apps.googleusercontent.com";
//    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
//        "droneroutesv-contentdelivery-mobilehub-1931080435";
//    // S3 BUCKET
//    public static final String AMAZON_S3_USER_FILES_BUCKET =
//        "droneroutesv-userfiles-mobilehub-1931080435";
//}
